# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and publish it to GH Pages.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish slidev

on:
  push:
    branches: [ "master" ]
  # allows us to run the workflow manually
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    # setup page run
    - name: Setup Pages
      uses: actions/configure-pages@v3
    # upload the artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload build folder
        path: 'dist/'
    # deploy the page!
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
